### PR TITLE
Add Tailwind CSS Standalone CLI utility filter

### PR DESCRIPTION
**Pull request by bennothommo**
This PR adds support for using the [Tailwind CSS standalone CLI utility](https://tailwindcss.com/blog/standalone-cli) as a filter in Assetic, allowing the building of Tailwind CSS through Assetic.

To allow this filter to work correctly, some adjustments have been made to the base Process filter class:

- The binary path of the filter can be specified on the fly now using the `setBinaryPath` method.
- The base directory that the process will run in can also be changed using the `setWorkingDirectory` method. This allows the Tailwind CSS utility to run within a certain folder, allowing the config to be determined automatically and for content files to be correctly found and parsed.

### CODE REVIEW

**Review by LukeTowers — APPROVED** [review]

**Comment by LukeTowers** [comment]
@bennothommo looks good! Feel free to merge and release when ready. 

Are you doing this in order to add core support for Tailwind to the Winter CMS Asset Combiner or just using it for a different project?

**Comment by LukeTowers** [comment]
@bennothommo one final thing needed is to add it to the list of filters in the README.

**Comment by bennothommo** [comment]
@LukeTowers honestly, it's just me finally getting around to doing some stuff I've been talking about for ages :joy:

**Comment by LukeTowers** [comment]
@bennothommo carry on then, much appreciated ❤️

**Pull request merged**
